// app/dashboard/interactions/[id]/page.jsx

"use client";

import React, { useEffect, useState, useCallback, useRef, use } from "react";
import { useRouter } from "next/navigation";
import { FaDownload } from "react-icons/fa";
import { Button } from "@/components/ui/button";
import InterationToolbar from "@/components/interation-toolbar";
import withAuth from "@/components/withAuth";
import CryptoJS from "crypto-js";
import { useSearchParams } from "next/navigation";
import { MODULES, PRIVILEGES } from "@/lib/constants/privileges";
import { getSelectedOrgIdsHeader } from "@/lib/client-org";

/* ── helper: decrypt session user once ── */
function getSessionUser() {
  try {
    const b = CryptoJS.AES.decrypt(sessionStorage.getItem("user") || "", "");
    return JSON.parse(b.toString(CryptoJS.enc.Utf8) || "{}");
  } catch { return {}; }
}
function getSessionTimezone() {
  try {
    const b = CryptoJS.AES.decrypt(sessionStorage.getItem("selectedTimezone") || "", "");
    return JSON.parse(b.toString(CryptoJS.enc.Utf8) || "null");
  } catch { return null; }
}

/* ── Map error codes to human-readable messages ── */
function errorCodeToMessage(code) {
  const map = {
    RULE_MISMATCH:       "No transcription rule matches this interaction. Check ANI, DNIS, extension, duration, and organization filters in Integration Workspace → Transcription.",
    NO_RULE:             "No transcription rule found for this interaction. Create a matching rule in Integration Workspace → Transcription.",
    NO_ENGINE:           "No STT engine configured in the transcription rule. Edit the rule and select an engine.",
    INVALID_API_KEY:     "STT engine API key is invalid or expired. Update the key in Integration Workspace → Transcription.",
    RATE_LIMIT:          "STT engine rate limit reached. Please wait a few minutes and retry.",
    STT_TIMEOUT:         "STT engine timed out. The audio may be too long. Try AWS Transcribe for longer recordings.",
    STT_ENGINE_ERROR:    "STT engine returned an error. Check the API key and engine configuration.",
    AUDIO_NOT_FOUND:     "Audio file not found. The recording may have been moved or deleted.",
    UNSUPPORTED_FORMAT:  "Unsupported audio format. Supported formats: WAV, MP3, MP4, M4A, OGG, FLAC, WEBM.",
    NETWORK_ERROR:       "Network error reaching STT engine. Check your internet connection and retry.",
    STORAGE_ERROR:       "Storage access error. Check S3/GCS credentials and bucket permissions.",
    FILE_TOO_LARGE:      "Audio file exceeds the 25 MB limit for this STT engine. Switch to AssemblyAI or AWS Transcribe for larger files.",
    INVALID_PATH:        "Invalid audio file path.",
    MISSING_FIELDS:      "Missing required fields for transcription.",
    ACCESS_CHECK_FAILED: "Could not verify transcription access. Please retry.",
    PROCESSING:          "Transcription is already being generated by another request.",
    UNKNOWN_ERROR:       "An unexpected error occurred during transcription.",
  };
  return map[code] || `Transcription error (${code}).`;
}

function isRetryable(code) {
  return ["RATE_LIMIT", "STT_TIMEOUT", "STT_ENGINE_ERROR", "NETWORK_ERROR",
          "ACCESS_CHECK_FAILED", "UNKNOWN_ERROR", "PROCESSING"].includes(code);
}

/* ── Poll transcription status until completed/failed or timeout ── */
async function pollTranscriptionStatus(interactionId, cancelledRef) {
  const MAX_POLLS  = 45;   // 45 × 4s = 3 minutes max
  const INTERVAL   = 4000; // 4 seconds between polls

  for (let i = 0; i < MAX_POLLS; i++) {
    // Check if component unmounted
    if (cancelledRef && cancelledRef.current) return { status: "cancelled" };

    await new Promise((r) => setTimeout(r, INTERVAL));

    if (cancelledRef && cancelledRef.current) return { status: "cancelled" };

    try {
      const res = await fetch(`/api/transcription-status/${interactionId}`, {
        headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}` },
      });
      if (!res.ok) continue;
      const data = await res.json();

      if (data.status === "completed" || data.status === "failed") {
        return data;
      }
      // "processing" or "pending" → keep polling
    } catch (_) {
      // network blip — keep polling
    }
  }
  return { status: "timeout" };
}

const InteractionInner = ({ params }) => {
  const { id } = use(params);

  // Hide the main layout scrollbar for this page only — restored on unmount
  useEffect(() => {
    const targets = [
      document.querySelector("main"),
      document.querySelector("body"),
      document.documentElement,
    ].filter(Boolean);
    const prevStyles = targets.map((el) => el.style.overflow);
    targets.forEach((el) => { el.style.overflow = "hidden"; });
    return () => {
      targets.forEach((el, i) => { el.style.overflow = prevStyles[i]; });
    };
  }, []);
  const searchParams = useSearchParams();
  const router = useRouter();

  const UserId = searchParams.get("user_id");
  const Status = searchParams.get("Status");

  const [data, setData]                     = useState(null);
  const [audioUrl, setAudioUrl]             = useState(null);
  const [audioFetching, setAudioFetching]   = useState(true);
  const [fileExtension, setFileExtension]   = useState(null);
  const [audioError, setAudioError]         = useState(null);
  const [archiveStatus, setArchiveStatus]   = useState(null); // 'needs_retrieval' | 'retrieving' | 'retrieved'
  const [sttGenerating, setSttGenerating]   = useState(false);
  const [sttError, setSttError]             = useState(null);       // { message, errorCode, retryable }
  const [sttStatus, setSttStatus]           = useState(null);       // "generating" | "done" | "failed" | "no_rule" | "processing"
  const [transcriptionMode, setTranscriptionMode] = useState(null); // "none" | "import" | "stt" | null
  const [grantedPrivileges, setGrantedPrivileges] = useState([]);
  const [privilegesLoaded, setPrivilegesLoaded]   = useState(false);
  // Separate stable state for transcription path — never reverts to null once set for an interaction
  const [stableTranscriptionPath, setStableTranscriptionPath] = useState(null);
  const stablePathInteractionRef = useRef(null); // tracks which interactionId the stable path belongs to
  const interactionListViewStateKey = "interactionListViewState";
  const audioBlobRef = useRef(null);
  const loadAudioRef = useRef(null);
  // Stable ref to the current interaction metadata — used by retry handler
  const interactionMetaRef = useRef(null);

  const hasPrivilege = (privId) =>
    grantedPrivileges.some((p) => p.PrivilegeId === privId);

  /* ── Retry transcription generation ── */
  const handleRetryTranscription = useCallback(async () => {
    const meta = interactionMetaRef.current;
    if (!meta) return;
    setSttError(null);
    setSttGenerating(true);
    setSttStatus("generating");
    try {
      const genRes = await fetch("/api/transcription-generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
        },
        body: JSON.stringify({
          interactionId: meta.iid,
          filePath:      meta.filePath,
          fileSourceType: meta.fileSourceType,
          platformId:    meta.platformId,
          appId:         meta.appId,
          ani:           meta.ani,
          dnis:          meta.dnis,
          extension:     meta.extension,
          duration:      meta.duration,
          orgId:         meta.orgId,
        }),
      });
      const genData = await genRes.json().catch(() => ({}));
      if (genRes.ok) {
        setSttStatus("done");
        setData((prev) =>
          prev
            ? { ...prev, transcriptionfilepath: genData.savedPath, transcription_source_type: meta.fileSourceType }
            : prev
        );
        fetch("/api/workFlow/getRuleStats", {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}` },
        }).catch(() => {});
      } else {
        const errCode = genData.errorCode || "UNKNOWN_ERROR";
        const errMsg  = genData.message   || errorCodeToMessage(errCode);
        setSttError({ message: errMsg, errorCode: errCode, retryable: genData.retryable ?? isRetryable(errCode) });
        setSttStatus("failed");
      }
    } catch (err) {
      setSttError({ message: "Network error — could not reach transcription service.", errorCode: "NETWORK_ERROR", retryable: true });
      setSttStatus("failed");
    } finally {
      setSttGenerating(false);
    }
  }, []);

  const normalizeInteraction = useCallback((row) => {
    if (!row) return null;
    return {
      ...row,
      id:          row.id ?? row.interactionId ?? row.interaction_id ?? row.callId ?? row.call_id,
      callId:      row.callId ?? row.call_id ?? row.interactionId ?? row.interaction_id,
      fileLocation:      row.fileLocation ?? row.file_location ?? row.filepath ?? null,
      fileSourceType:    row.fileSourceType ?? row.file_source_type ?? null,
      transcriptionfilepath:     row.transcriptionfilepath ?? row.transcription_file_path ?? null,
      transcription_source_type: row.transcription_source_type ?? null,
      transcription_status:      row.transcription_status ?? null,
      transcription_error:       row.transcription_error ?? null,
      audioStartTime: row.audioStartTime ?? row.audio_start_time ?? null,
      audioEndTime:   row.audioEndTime   ?? row.audio_end_time   ?? null,
      localStartTime: row.localStartTime ?? row.local_start_time ?? null,
      localEndTime:   row.localEndTime   ?? row.local_end_time   ?? null,
      personalName:   row.personalName   ?? row.personal_name    ?? null,
      pbxLoginId:     row.pbxLoginId     ?? row.pbx_login_id     ?? null,
      audioModuleNo:  row.audioModuleNo  ?? row.audio_module_no  ?? null,
      audioChannelNo: row.audioChannelNo ?? row.audio_ch_no      ?? null,
      agentId:        row.agentId        ?? row.agent_id         ?? null,
      switchCallId:   row.switchCallId   ?? row.switch_call_id   ?? null,
      Platformid:     row.Platformid     ?? row.platformId       ?? null,
      appid:          row.appid          ?? row.appId            ?? null,
    };
  }, []);

  /* ── Fetch privileges + interaction in parallel ── */
  useEffect(() => {
    let cancelled = false;
    const cancelledBox = { current: false }; // shared with pollTranscriptionStatus

    const run = async () => {
      const user     = getSessionUser();
      const timezone = getSessionTimezone();
      const userId   = user?.userId || null;
      const userName = user?.userFullName || null;

      // Reset stale state immediately
      setAudioUrl(null);
      setAudioError(null);
      setFileExtension(null);
      setAudioFetching(true);
      setData(null);
      // Reset stable transcription path only when switching to a NEW interaction
      if (stablePathInteractionRef.current !== id) {
        stablePathInteractionRef.current = id;
        setStableTranscriptionPath(null);
      }
      audioBlobRef.current = null;

      // ── Run privileges + interaction fetch in parallel ──
      const [privResult, interactionResult] = await Promise.allSettled([
        fetch("/api/privileges", {
          headers: {
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
            loggedInUserId: userId,
            moduleId: MODULES.INTERACTION,
            orgId: sessionStorage.getItem("selectedOrgId") || "",
            orgIds: getSelectedOrgIdsHeader(),
          },
        }).then((r) => r.json()),

        fetch(`/api/interactions/${id}`, {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
            loggedInUserId: userId || "",
            userName: userName || "",
            timezone,
            requestType: "SELECTED",
            orgIds: getSelectedOrgIdsHeader(),
          },
        }),
      ]);

      if (cancelled) return;

      // Handle privileges
      const privileges = privResult.status === "fulfilled"
        ? (privResult.value?.privileges || [])
        : [];
      setGrantedPrivileges(privileges);
      setPrivilegesLoaded(true);

      const canView = privileges.some((p) => p.PrivilegeId === PRIVILEGES.VIEW);
      if (!canView) return;

      // Handle interaction data
      let resolvedData = null;
      if (interactionResult.status === "fulfilled") {
        const res = interactionResult.value;
        if (res.status === 404) {
          // Fallback search
          try {
            const fb = await fetch(`/api/interactions`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
              },
              body: JSON.stringify({
                pageNo: 1, rowCountPerPage: 1, search: id,
                queryType: 1, currentUserId: userId, timezone,
                ActiveStatus: 0, privilegeId: 0,
              }),
            });
            if (fb.ok) {
              const fbData = await fb.json();
              if (fbData?.interactions?.length) resolvedData = fbData.interactions[0];
            }
          } catch (_) {}
        } else if (res.ok) {
          const d = await res.json();
          if (d?.interactions?.length) resolvedData = d.interactions[0];
        }
      }

      if (!resolvedData || cancelled) return;

      const normalized = normalizeInteraction(resolvedData);
      if (cancelled) return;

      // If the DB already has a transcription path, lock it immediately — before any async work
      if (
        normalized.transcriptionfilepath &&
        !normalized.transcriptionfilepath.startsWith("ERROR:") &&
        normalized.transcriptionfilepath !== "PROCESSING"
      ) {
        setStableTranscriptionPath(normalized.transcriptionfilepath);
      }

      const filePath       = normalized.fileLocation;
      const fileSourceType = normalized.fileSourceType;
      const iid            = normalized.id || id;
      const platformId     = normalized.Platformid ?? normalized.platformId ?? resolvedData?.Platformid ?? resolvedData?.platformId ?? null;
      const appId          = normalized.appid ?? normalized.appId ?? resolvedData?.appid ?? resolvedData?.Appid ?? null;

      // Set data immediately so UI renders with call info
      setData(normalized);

      if (!filePath) return;

      const ext = filePath.split(".").pop().toLowerCase();
      setFileExtension(ext);

      // ── Load audio — resolve presigned URL first for S3/GCS, use direct URL for local ──
      const loadAudio = async (isPoll = false) => {
        if (cancelled) return;
        if (!cancelled && !isPoll) {
          setAudioFetching(true);
          setAudioError(null);
          setArchiveStatus(null);
        }
        const isM4a = ext === "m4a";
        const apiUrl = `/api/audio?filePath=${encodeURIComponent(filePath)}&interactionId=${iid}&fileSourceType=${encodeURIComponent(fileSourceType ?? "")}&actionType=load${isM4a ? "&stream=1" : ""}&auth=${encodeURIComponent(process.env.NEXT_PUBLIC_API_TOKEN || "")}`;
        try {
          const res = await fetch(apiUrl, {
            headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}` },
          });
          if (!res.ok) {
            let errMsg = "No audio at the path.";
            try {
              const errData = await res.json();
              if (errData?.message) errMsg = errData.message;
            } catch (_) {}
            throw new Error(errMsg);
          }
          const contentType = res.headers.get("content-type") || "";
          if (contentType.includes("application/json")) {
            const data = await res.json();
            if (data.status === "needs_retrieval") {
              if (!cancelled) {
                setAudioUrl(null);
                setAudioError("The call needs to be retrieved.");
                setArchiveStatus("needs_retrieval");
              }
            } else if (data.status === "retrieving") {
              if (!cancelled) {
                setAudioUrl(null);
                setAudioError("The call is retrieving...");
                setArchiveStatus("retrieving");
                // Schedule next status check poll
                setTimeout(() => {
                  loadAudio(true);
                }, 15000);
              }
            } else {
              if (!cancelled) {
                // ── Convert presigned S3/GCS URL to a blob: URL ───────────────────────────
                // Next.js 16 rejects long presigned URLs (with X-Amz-* query params) as
                // audio/video src due to its built-in URL safety check. Converting to a
                // local blob: URL bypasses this check entirely.
                let playbackUrl = data.url;
                const isVideo = ["mp4", "mkv", "m4v", "avi", "mov", "3gp", "flv", "wmv", "webm", "m4a"].includes(ext);
                // Convert to blob if it is not video, or if it is m4a (to bypass browser file extension blocks on native video element)
                const shouldConvertBlob = !isVideo || ext === "m4a";
                if (shouldConvertBlob) {
                  try {
                    const audioRes = await fetch(data.url);
                    if (audioRes.ok) {
                      const blob = await audioRes.blob();
                      const finalBlob = ext === "m4a" ? new Blob([blob], { type: "video/mp4" }) : blob;
                      playbackUrl = URL.createObjectURL(finalBlob);
                    }
                  } catch (blobErr) {
                    // Fallback to direct URL if blob conversion fails (e.g. CORS)
                    playbackUrl = data.url;
                  }
                }
                setAudioUrl(playbackUrl);
                setArchiveStatus("retrieved");
                setAudioError(null);
              }
            }
          } else {
            // Local/network — API is streaming bytes, use the API URL directly
            if (!cancelled) {
              setAudioUrl(apiUrl);
              setArchiveStatus("retrieved");
              setAudioError(null);
            }
          }
        } catch (err) {
          console.error("[loadAudio] error:", err.message);
          if (!cancelled && !isPoll) {
            setAudioError(err.message || "No audio at the path.");
            setAudioUrl(null);
            setArchiveStatus(null);
          }
        } finally {
          if (!cancelled && !isPoll) setAudioFetching(false);
        }
      };
      loadAudioRef.current = loadAudio;

      // ── Transcription config + generate in background ──
      const loadTranscription = async () => {
        if (!platformId || !appId) return;
        try {
          // Build interaction-level filter params for rule matching
          const params = new URLSearchParams({
            appId: String(appId),
          });
          if (normalized.ani)            params.set("ani",         String(normalized.ani));
          if (normalized.dnis)           params.set("dnis",        String(normalized.dnis));
          if (normalized.extension)      params.set("extension",   String(normalized.extension));
          if (normalized.duration)       params.set("duration",    String(normalized.duration));
          if (normalized.organizationId) params.set("orgId",       String(normalized.organizationId));
          if (normalized.agentId)        params.set("agentId",     String(normalized.agentId));

          const cfgRes = await fetch(
            // Bust cache when no existing path — ensures pending interactions
            // always get a fresh rule check, not a cached "none"
            `/api/transcription-config?${params.toString()}${!normalized.transcriptionfilepath ? "&bust=1" : ""}`,
            { headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}` } },
          );
          if (!cfgRes.ok) return;
          const cfg = await cfgRes.json();

          if (!cancelled) setTranscriptionMode(cfg.mode);

          let transcriptionPath       = normalized.transcriptionfilepath || null;
          let transcriptionSourceType = normalized.transcription_source_type || null;
          const dbStatus              = String(normalized.transcription_status || "").toUpperCase();

          // ── Interpret existing DB state ────────────────────────────────
          if (dbStatus === "PROCESSING" || transcriptionPath === "PROCESSING") {
            if (!cancelled) {
              setSttGenerating(true);
              setSttStatus("processing");
            }
            // Poll until the other request finishes (max 3 min, every 4s)
            const pollResult = await pollTranscriptionStatus(iid, cancelledBox);
            if (cancelled) return;
            if (pollResult.status === "completed") {
              if (!cancelled) {
                setSttGenerating(false);
                setSttStatus("done");
                setData((prev) => prev ? {
                  ...prev,
                  transcriptionfilepath:     pollResult.transcriptionfilepath,
                  transcription_source_type: pollResult.transcription_source_type,
                  transcription_status:      "COMPLETED"
                } : prev);
                // Also update stable path
                if (
                  pollResult.transcriptionfilepath &&
                  !pollResult.transcriptionfilepath.startsWith("ERROR:") &&
                  pollResult.transcriptionfilepath !== "PROCESSING"
                ) {
                  setStableTranscriptionPath(pollResult.transcriptionfilepath);
                }
              }
            } else if (pollResult.status === "failed") {
              const errCode = pollResult.errorCode || "UNKNOWN_ERROR";
              if (!cancelled) {
                setSttGenerating(false);
                setSttError({ message: errorCodeToMessage(errCode), errorCode: errCode, retryable: isRetryable(errCode) });
                setSttStatus("failed");
                setData((prev) => prev ? { ...prev, transcriptionfilepath: null, transcription_status: "FAILED" } : prev);
              }
            } else {
              // Timed out still processing — let user know
              if (!cancelled) {
                setSttGenerating(false);
                setSttError({ message: "Transcription is taking longer than expected. Please refresh the page in a minute.", errorCode: "STT_TIMEOUT", retryable: true });
                setSttStatus("failed");
              }
            }
            return;

          } else if (dbStatus === "FAILED" || transcriptionPath?.startsWith("ERROR:")) {
            const errorCode = dbStatus === "FAILED" ? (normalized.transcription_error || "UNKNOWN_ERROR") : transcriptionPath.slice(6);
            const friendlyMsg = errorCodeToMessage(errorCode);
            if (!cancelled) {
              setSttError({ message: friendlyMsg, errorCode, retryable: isRetryable(errorCode) });
              setSttStatus("failed");
            }
            // Update data so AudioPlayer knows there's no real path
            if (!cancelled) {
              setData((prev) => prev
                ? { ...prev, transcriptionfilepath: null, transcription_source_type: null, transcription_status: "FAILED" }
                : prev
              );
            }
            return;

          } else if (dbStatus === "COMPLETED" || transcriptionPath?.trim()) {
            // Real path exists — just load it, no generation needed
            if (!cancelled) setSttStatus("done");

          } else if (cfg.mode === "none") {
            if (!cancelled) setSttStatus("no_rule");
            transcriptionPath = null;

          } else if (cfg.mode === "import") {
            transcriptionPath = null;

          } else if (cfg.mode === "stt") {
            // No path yet → generate now
            if (!cancelled) {
              setSttGenerating(true);
              setSttStatus("generating");
              setSttError(null);
            }

            // Store meta for retry
            interactionMetaRef.current = {
              iid, filePath, fileSourceType, platformId, appId,
              ani:       normalized.ani            || null,
              dnis:      normalized.dnis           || null,
              extension: normalized.extension      || null,
              duration:  normalized.duration       || null,
              orgId:     normalized.organizationId || null,
            };

            try {
              const genRes = await fetch("/api/transcription-generate", {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
                },
                body: JSON.stringify({
                  interactionId: iid,
                  filePath,
                  fileSourceType,
                  platformId,
                  appId,
                  ani:       normalized.ani            || null,
                  dnis:      normalized.dnis           || null,
                  extension: normalized.extension      || null,
                  duration:  normalized.duration       || null,
                  orgId:     normalized.organizationId || null,
                }),
              });

              const genData = await genRes.json().catch(() => ({}));

              if (genRes.ok) {
                transcriptionPath       = genData.savedPath;
                transcriptionSourceType = fileSourceType;
                if (!cancelled) setSttStatus("done");
                // Lock stable path as soon as generation succeeds
                if (
                  transcriptionPath &&
                  !transcriptionPath.startsWith("ERROR:") &&
                  transcriptionPath !== "PROCESSING"
                ) {
                  setStableTranscriptionPath(transcriptionPath);
                }
                // Update rule stats (fire & forget)
                fetch("/api/workFlow/getRuleStats", {
                  method: "POST",
                  headers: { "Content-Type": "application/json", Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}` },
                }).catch(() => {});
              } else {
                const errCode = genData.errorCode || "UNKNOWN_ERROR";
                const errMsg  = genData.message   || errorCodeToMessage(errCode);
                if (!cancelled) {
                  setSttError({ message: errMsg, errorCode: errCode, retryable: genData.retryable ?? isRetryable(errCode) });
                  setSttStatus("failed");
                }
                transcriptionPath = null;
              }
            } catch (genErr) {
              if (!cancelled) {
                setSttError({ message: "Network error — could not reach transcription service. Check your connection.", errorCode: "NETWORK_ERROR", retryable: true });
                setSttStatus("failed");
              }
              transcriptionPath = null;
            } finally {
              if (!cancelled) setSttGenerating(false);
            }
          }

          if (!cancelled) {
            setData((prev) =>
              prev
                ? { ...prev, transcriptionfilepath: transcriptionPath, transcription_source_type: transcriptionSourceType }
                : prev,
            );
            // Update stable path only if we got a real one (never overwrite with null)
            if (
              transcriptionPath &&
              !transcriptionPath.startsWith("ERROR:") &&
              transcriptionPath !== "PROCESSING"
            ) {
              setStableTranscriptionPath(transcriptionPath);
            }
          }
        } catch (cfgErr) {
          console.error("[transcription] config error:", cfgErr.message);
        }
      };

      // Run audio + transcription in parallel — audio URL set immediately
      loadAudio();
      loadTranscription();
    };

    run();
    return () => { cancelled = true; cancelledBox.current = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const handleRetrieveCall = useCallback(async () => {
    const fileSourceType = data?.fileSourceType || data?.file_source_type;
    const iid = data?.id || id;
    if (!data?.fileLocation) return;
    
    try {
      setAudioFetching(true);
      setAudioError(null);
      const res = await fetch(`/api/audio?filePath=${encodeURIComponent(data.fileLocation)}&interactionId=${iid}&fileSourceType=${encodeURIComponent(fileSourceType ?? "")}&actionType=retrieve&auth=${encodeURIComponent(process.env.NEXT_PUBLIC_API_TOKEN || "")}`, {
        headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}` },
      });
      if (res.ok) {
        const resData = await res.json();
        if (resData.status === "retrieving") {
          setArchiveStatus("retrieving");
          setAudioError("The call is retrieving...");
          setAudioUrl(null);
          // Start the polling check
          setTimeout(() => {
            loadAudioRef.current?.(true);
          }, 15000);
        }
      } else {
        console.error("Retrieve request failed");
        setAudioError("Failed to initiate retrieval.");
      }
    } catch (err) {
      console.error("[retrieveCall] error:", err.message);
      setAudioError("Failed to initiate retrieval.");
    } finally {
      setAudioFetching(false);
    }
  }, [data, id]);

  const downloadAudio = async () => {
    const user = getSessionUser();
    const iid  = data?.id || id;
    const cid  = data?.callId || data?.call_id || iid; // prefer callId for filenames
    if (!data?.fileLocation) return;

    const tPath    = stableTranscriptionPath || data?.transcriptionfilepath;
    const tSrcType = data?.transcription_source_type || data?.fileSourceType || "local";
    const hasTranscription = !!tPath?.trim();

    try {
      const res = await fetch("/api/interactions/download", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization:  `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
          loggedInUserId: user?.userId,
          userName:       user?.userFullName,
        },
        body: JSON.stringify({
          fileLocation: data.fileLocation,
          fileSourceType: data.fileSourceType,
          transcriptionPath: hasTranscription ? tPath : null,
          transcriptionSourceType: hasTranscription ? tSrcType : null,
          callId: cid,
          fileExtension: fileExtension || "wav"
        })
      });

      if (res.ok) {
        const blob = await res.blob();
        const downloadUrl = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = downloadUrl;
        a.download = hasTranscription ? `${cid}.zip` : `${cid}.${fileExtension || "wav"}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000);
      } else {
        console.error("[downloadAudio] API error:", res.status);
      }
    } catch (err) {
      console.error("[downloadAudio] error:", err.message);
    }
  };

  /* ── Cleanup blob on unmount ── */
  useEffect(() => {
    return () => {
      if (audioBlobRef.current) URL.revokeObjectURL(audioBlobRef.current);
    };
  }, []);

  if (!privilegesLoaded) return <p className="text-xs text-muted-foreground p-4">Loading...</p>;
  if (!hasPrivilege(PRIVILEGES.VIEW)) return <p className="text-xs text-muted-foreground p-4">Unauthorized.</p>;

  const safeData = data || { id, callId: null, fileLocation: null, fileSourceType: null, transcriptionfilepath: null };

  return (
    <div className="flex flex-col overflow-hidden" style={{ height: "calc(100vh - 88px)" }}>
      <InterationToolbar
        formData={safeData}
        Status={Status}
        audioUrl={audioUrl}
        audioFetching={audioFetching}
        fileExtension={fileExtension}
        audioError={audioError}
        sttGenerating={sttGenerating}
        sttError={sttError}
        sttStatus={sttStatus}
        transcriptionMode={transcriptionMode}
        grantedPrivileges={grantedPrivileges}
        onRetryTranscription={handleRetryTranscription}
        stableTranscriptionPath={stableTranscriptionPath}
        archiveStatus={archiveStatus}
        onRetrieve={handleRetrieveCall}
        showTranscription={true}
        onBack={() => {
          if (sessionStorage.getItem(interactionListViewStateKey)) {
            router.push("/dashboard/interactions");
            return;
          }
          router.back();
        }}
        downloadNode={
          <Button
            onClick={downloadAudio}
            disabled={!audioUrl || !!audioError || audioFetching}
            className="text-xs px-3 gap-1.5 h-7 flex items-center shadow-md rounded-lg font-medium"
          >
            <FaDownload className="h-3 w-3" /> Download Call
          </Button>
        }
      />
    </div>
  );
};

const Interaction = ({ params }) => <InteractionInner params={params} />;

export default withAuth(Interaction);
