"use client";

import React, { useEffect, useState, useCallback, useRef } from "react";
import { FaDownload } from "react-icons/fa";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import InterationToolbar from "@/components/interation-toolbar";
import CryptoJS from "crypto-js";
import { MODULES, PRIVILEGES } from "@/lib/constants/privileges";
import { getSelectedOrgIdsHeader } from "@/lib/client-org";
import {
  Dialog,
  DialogContent,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";

function getSessionUser() {
  try {
    const b = CryptoJS.AES.decrypt(sessionStorage.getItem("user") || "", "");
    return JSON.parse(b.toString(CryptoJS.enc.Utf8) || "{}");
  } catch {
    return {};
  }
}

function getSessionTimezone() {
  try {
    const b = CryptoJS.AES.decrypt(
      sessionStorage.getItem("selectedTimezone") || "",
      ""
    );
    return JSON.parse(b.toString(CryptoJS.enc.Utf8) || "null");
  } catch {
    return null;
  }
}

function errorCodeToMessage(code) {
  const map = {
    RULE_MISMATCH:
      "No transcription rule matches this interaction. Check ANI, DNIS, extension, duration, and organization filters in Integration Workspace → Transcription.",
    NO_RULE:
      "No transcription rule found for this interaction. Create a matching rule in Integration Workspace → Transcription.",
    NO_ENGINE:
      "No STT engine configured in the transcription rule. Edit the rule and select an engine.",
    INVALID_API_KEY:
      "STT engine API key is invalid or expired. Update the key in Integration Workspace → Transcription.",
    RATE_LIMIT:
      "STT engine rate limit reached. Please wait a few minutes and retry.",
    STT_TIMEOUT:
      "STT engine timed out. The audio may be too long. Try AWS Transcribe for longer recordings.",
    STT_ENGINE_ERROR:
      "STT engine returned an error. Check the API key and engine configuration.",
    AUDIO_NOT_FOUND:
      "Audio file not found. The recording may have been moved or deleted.",
    UNSUPPORTED_FORMAT:
      "Unsupported audio format. Supported formats: WAV, MP3, MP4, M4A, OGG, FLAC, WEBM.",
    NETWORK_ERROR:
      "Network error reaching STT engine. Check your internet connection and retry.",
    STORAGE_ERROR:
      "Storage access error. Check S3/GCS credentials and bucket permissions.",
    FILE_TOO_LARGE:
      "Audio file exceeds the 25 MB limit for this STT engine. Switch to AssemblyAI or AWS Transcribe for larger files.",
    INVALID_PATH: "Invalid audio file path.",
    MISSING_FIELDS: "Missing required fields for transcription.",
    ACCESS_CHECK_FAILED: "Could not verify transcription access. Please retry.",
    PROCESSING:
      "Transcription is already being generated by another request.",
    UNKNOWN_ERROR: "An unexpected error occurred during transcription.",
  };
  return map[code] || `Transcription error (${code}).`;
}

function isRetryable(code) {
  return [
    "RATE_LIMIT",
    "STT_TIMEOUT",
    "STT_ENGINE_ERROR",
    "NETWORK_ERROR",
    "ACCESS_CHECK_FAILED",
    "UNKNOWN_ERROR",
    "PROCESSING",
  ].includes(code);
}

async function pollTranscriptionStatus(interactionId, cancelledRef) {
  const MAX_POLLS = 45;
  const INTERVAL = 4000;

  for (let i = 0; i < MAX_POLLS; i++) {
    if (cancelledRef && cancelledRef.current) return { status: "cancelled" };
    await new Promise((r) => setTimeout(r, INTERVAL));
    if (cancelledRef && cancelledRef.current) return { status: "cancelled" };

    try {
      const res = await fetch(`/api/transcription-status/${interactionId}`, {
        headers: {
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
        },
      });
      if (!res.ok) continue;
      const data = await res.json();

      if (data.status === "completed" || data.status === "failed") {
        return data;
      }
    } catch (_) {}
  }
  return { status: "timeout" };
}

export default function InteractionPlayer({ interactionId, fileLocation: initialFileLocation, fileSourceType: initialFileSourceType, onClose }) {
  // Derive file extension immediately from the prop so the correct player
  // (audio vs video) renders on the first frame without waiting for metadata.
  const getExtFromPath = (p) => (p ? p.split(".").pop().toLowerCase() : null);
  const initialExt = getExtFromPath(initialFileLocation);

  const [data, setData] = useState(null);
  const [audioUrl, setAudioUrl] = useState(null);
  const [audioFetching, setAudioFetching] = useState(true);
  const [fileExtension, setFileExtension] = useState(initialExt);
  const [audioError, setAudioError] = useState(null);
  const [archiveStatus, setArchiveStatus] = useState(null);
  const [sttGenerating, setSttGenerating] = useState(false);
  const [sttError, setSttError] = useState(null);
  const [sttStatus, setSttStatus] = useState(null);
  const [transcriptionMode, setTranscriptionMode] = useState(null);
  const [grantedPrivileges, setGrantedPrivileges] = useState([]);
  const [privilegesLoaded, setPrivilegesLoaded] = useState(false);
  const [stableTranscriptionPath, setStableTranscriptionPath] = useState(null);
  const stablePathInteractionRef = useRef(null);
  const audioBlobRef = useRef(null);
  const loadAudioRef = useRef(null);
  const interactionMetaRef = useRef(null);

  const id = interactionId;

  const hasPrivilege = (privId) =>
    grantedPrivileges.some((p) => p.PrivilegeId === privId);

  const handleRetryTranscription = useCallback(async () => {
    const meta = interactionMetaRef.current;
    if (!meta) return;
    setSttError(null);
    setSttGenerating(true);
    setSttStatus("generating");
    try {
      const genRes = await fetch("/api/transcription-generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
        },
        body: JSON.stringify({
          interactionId: meta.iid,
          filePath: meta.filePath,
          fileSourceType: meta.fileSourceType,
          platformId: meta.platformId,
          appId: meta.appId,
          ani: meta.ani,
          dnis: meta.dnis,
          extension: meta.extension,
          duration: meta.duration,
          orgId: meta.orgId,
        }),
      });
      const genData = await genRes.json().catch(() => ({}));
      if (genRes.ok) {
        setSttStatus("done");
        setData((prev) =>
          prev
            ? {
                ...prev,
                transcriptionfilepath: genData.savedPath,
                transcription_source_type: meta.fileSourceType,
              }
            : prev
        );
        fetch("/api/workFlow/getRuleStats", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
          },
        }).catch(() => {});
      } else {
        const errCode = genData.errorCode || "UNKNOWN_ERROR";
        const errMsg = genData.message || errorCodeToMessage(errCode);
        setSttError({
          message: errMsg,
          errorCode: errCode,
          retryable: genData.retryable ?? isRetryable(errCode),
        });
        setSttStatus("failed");
      }
    } catch (err) {
      setSttError({
        message: "Network error — could not reach transcription service.",
        errorCode: "NETWORK_ERROR",
        retryable: true,
      });
      setSttStatus("failed");
    } finally {
      setSttGenerating(false);
    }
  }, []);

  const normalizeInteraction = useCallback((row) => {
    if (!row) return null;
    return {
      ...row,
      id:
        row.id ??
        row.interactionId ??
        row.interaction_id ??
        row.callId ??
        row.call_id,
      callId:
        row.callId ?? row.call_id ?? row.interactionId ?? row.interaction_id,
      fileLocation: row.fileLocation ?? row.file_location ?? row.filepath ?? null,
      fileSourceType: row.fileSourceType ?? row.file_source_type ?? null,
      transcriptionfilepath:
        row.transcriptionfilepath ?? row.transcription_file_path ?? null,
      transcription_source_type: row.transcription_source_type ?? null,
      transcription_status: row.transcription_status ?? null,
      transcription_error: row.transcription_error ?? null,
      audioStartTime: row.audioStartTime ?? row.audio_start_time ?? null,
      audioEndTime: row.audioEndTime ?? row.audio_end_time ?? null,
      localStartTime: row.localStartTime ?? row.local_start_time ?? null,
      localEndTime: row.localEndTime ?? row.local_end_time ?? null,
      personalName: row.personalName ?? row.personal_name ?? null,
      pbxLoginId: row.pbxLoginId ?? row.pbx_login_id ?? null,
      audioModuleNo: row.audioModuleNo ?? row.audio_module_no ?? null,
      audioChannelNo: row.audioChannelNo ?? row.audio_ch_no ?? null,
      agentId: row.agentId ?? row.agent_id ?? null,
      switchCallId: row.switchCallId ?? row.switch_call_id ?? null,
      Platformid: row.Platformid ?? row.platformId ?? null,
      appid: row.appid ?? row.appId ?? null,
    };
  }, []);

  useEffect(() => {
    if (!id) return;

    let cancelled = false;
    const cancelledBox = { current: false };

    const run = async () => {
      const user = getSessionUser();
      const timezone = getSessionTimezone();
      const userId = user?.userId || null;
      const userName = user?.userFullName || null;

      setAudioUrl(null);
      setAudioError(null);
      // Reset to the extension already known from the prop (not null) so the
      // correct player type (audio vs video) renders immediately without flash.
      setFileExtension(initialExt);
      setAudioFetching(true);
      setData(null);

      if (stablePathInteractionRef.current !== id) {
        stablePathInteractionRef.current = id;
        setStableTranscriptionPath(null);
      }
      audioBlobRef.current = null;

      const [privResult, interactionResult] = await Promise.allSettled([
        fetch("/api/privileges", {
          headers: {
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
            loggedInUserId: userId,
            moduleId: MODULES.INTERACTION,
            orgId: sessionStorage.getItem("selectedOrgId") || "",
            orgIds: getSelectedOrgIdsHeader(),
          },
        }).then((r) => r.json()),

        fetch(`/api/interactions/${id}`, {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
            loggedInUserId: userId || "",
            userName: userName || "",
            timezone,
            requestType: "SELECTED",
            orgIds: getSelectedOrgIdsHeader(),
          },
        }),
      ]);

      if (cancelled) return;

      const privileges =
        privResult.status === "fulfilled"
          ? privResult.value?.privileges || []
          : [];
      setGrantedPrivileges(privileges);
      setPrivilegesLoaded(true);

      const canView = privileges.some((p) => p.PrivilegeId === PRIVILEGES.VIEW);
      if (!canView) return;

      let resolvedData = null;
      if (interactionResult.status === "fulfilled") {
        const res = interactionResult.value;
        if (res.status === 404) {
          try {
            const fb = await fetch(`/api/interactions`, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
              },
              body: JSON.stringify({
                pageNo: 1,
                rowCountPerPage: 1,
                search: id,
                queryType: 1,
                currentUserId: userId,
                timezone,
                ActiveStatus: 0,
                privilegeId: 0,
              }),
            });
            if (fb.ok) {
              const fbData = await fb.json();
              if (fbData?.interactions?.length)
                resolvedData = fbData.interactions[0];
            }
          } catch (_) {}
        } else if (res.ok) {
          const d = await res.json();
          if (d?.interactions?.length) resolvedData = d.interactions[0];
        }
      }

      if (!resolvedData || cancelled) return;

      const normalized = normalizeInteraction(resolvedData);
      if (cancelled) return;

      if (
        normalized.transcriptionfilepath &&
        !normalized.transcriptionfilepath.startsWith("ERROR:") &&
        normalized.transcriptionfilepath !== "PROCESSING"
      ) {
        setStableTranscriptionPath(normalized.transcriptionfilepath);
      }

      const filePath = normalized.fileLocation;
      const fileSourceType = normalized.fileSourceType;
      const iid = normalized.id || id;
      const platformId =
        normalized.Platformid ??
        normalized.platformId ??
        resolvedData?.Platformid ??
        resolvedData?.platformId ??
        null;
      const appId =
        normalized.appid ??
        normalized.appId ??
        resolvedData?.appid ??
        resolvedData?.Appid ??
        null;

      setData(normalized);

      if (!filePath) return;

      const ext = filePath.split(".").pop().toLowerCase();
      // Only update extension state if it wasn't already known from the prop
      if (!fileExtension) setFileExtension(ext);

      const loadAudio = async (isPoll = false) => {
        if (cancelled) return;
        if (!cancelled && !isPoll) {
          setAudioFetching(true);
          setAudioError(null);
          setArchiveStatus(null);
        }
        const apiUrl = `/api/audio?filePath=${encodeURIComponent(
          filePath
        )}&interactionId=${iid}&fileSourceType=${encodeURIComponent(
          fileSourceType ?? ""
        )}&actionType=load&stream=1&auth=${encodeURIComponent(
          process.env.NEXT_PUBLIC_API_TOKEN || ""
        )}`;
        try {
          const res = await fetch(apiUrl, {
            headers: {
              Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
            },
          });
          if (!res.ok) {
            let errMsg = "No audio at the path.";
            try {
              const errData = await res.json();
              if (errData?.message) errMsg = errData.message;
            } catch (_) {}
            throw new Error(errMsg);
          }
          const contentType = res.headers.get("content-type") || "";
          if (contentType.includes("application/json")) {
            const data = await res.json();
            if (data.status === "needs_retrieval") {
              if (!cancelled) {
                setAudioUrl(null);
                setAudioError("The call needs to be retrieved.");
                setArchiveStatus("needs_retrieval");
              }
            } else if (data.status === "retrieving") {
              if (!cancelled) {
                setAudioUrl(null);
                setAudioError("The call is retrieving...");
                setArchiveStatus("retrieving");
                setTimeout(() => {
                  loadAudio(true);
                }, 15000);
              }
            } else {
              if (!cancelled) {
                setAudioUrl(data.url);
                setArchiveStatus("retrieved");
                setAudioError(null);
              }
            }
          } else {
            if (!cancelled) {
              setAudioUrl(apiUrl);
              setArchiveStatus("retrieved");
              setAudioError(null);
            }
          }
        } catch (err) {
          console.error("Playback error.");
          if (!cancelled && !isPoll) {
            setAudioError(err.message || "No audio at the path.");
            setAudioUrl(null);
            setArchiveStatus(null);
          }
        } finally {
          if (!cancelled && !isPoll) setAudioFetching(false);
        }
      };
      loadAudioRef.current = loadAudio;

      const loadTranscription = async () => {
        if (!platformId || !appId) return;
        try {
          const params = new URLSearchParams({
            appId: String(appId),
          });
          if (normalized.ani) params.set("ani", String(normalized.ani));
          if (normalized.dnis) params.set("dnis", String(normalized.dnis));
          if (normalized.extension)
            params.set("extension", String(normalized.extension));
          if (normalized.duration)
            params.set("duration", String(normalized.duration));
          if (normalized.organizationId)
            params.set("orgId", String(normalized.organizationId));
          if (normalized.agentId)
            params.set("agentId", String(normalized.agentId));

          const cfgRes = await fetch(
            `/api/transcription-config?${params.toString()}${
              !normalized.transcriptionfilepath ? "&bust=1" : ""
            }`,
            {
              headers: {
                Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
              },
            }
          );
          if (!cfgRes.ok) return;
          const cfg = await cfgRes.json();

          if (!cancelled) setTranscriptionMode(cfg.mode);

          let transcriptionPath = normalized.transcriptionfilepath || null;
          let transcriptionSourceType =
            normalized.transcription_source_type || null;
          const dbStatus = String(
            normalized.transcription_status || ""
          ).toUpperCase();

          if (
            dbStatus === "PROCESSING" ||
            transcriptionPath === "PROCESSING"
          ) {
            if (!cancelled) {
              setSttGenerating(true);
              setSttStatus("processing");
            }
            const pollResult = await pollTranscriptionStatus(iid, cancelledBox);
            if (cancelled) return;
            if (pollResult.status === "completed") {
              if (!cancelled) {
                setSttGenerating(false);
                setSttStatus("done");
                setData((prev) =>
                  prev
                    ? {
                        ...prev,
                        transcriptionfilepath: pollResult.transcriptionfilepath,
                        transcription_source_type:
                          pollResult.transcription_source_type,
                        transcription_status: "COMPLETED",
                      }
                    : prev
                );
                if (
                  pollResult.transcriptionfilepath &&
                  !pollResult.transcriptionfilepath.startsWith("ERROR:") &&
                  pollResult.transcriptionfilepath !== "PROCESSING"
                ) {
                  setStableTranscriptionPath(pollResult.transcriptionfilepath);
                }
              }
            } else if (pollResult.status === "failed") {
              const errCode = pollResult.errorCode || "UNKNOWN_ERROR";
              if (!cancelled) {
                setSttGenerating(false);
                setSttError({
                  message: errorCodeToMessage(errCode),
                  errorCode: errCode,
                  retryable: isRetryable(errCode),
                });
                setSttStatus("failed");
                setData((prev) =>
                  prev
                    ? {
                        ...prev,
                        transcriptionfilepath: null,
                        transcription_status: "FAILED",
                      }
                    : prev
                );
              }
            } else {
              if (!cancelled) {
                setSttGenerating(false);
                setSttError({
                  message:
                    "Transcription is taking longer than expected. Please refresh the page in a minute.",
                  errorCode: "STT_TIMEOUT",
                  retryable: true,
                });
                setSttStatus("failed");
              }
            }
            return;
          } else if (
            dbStatus === "FAILED" ||
            transcriptionPath?.startsWith("ERROR:")
          ) {
            const errorCode =
              dbStatus === "FAILED"
                ? normalized.transcription_error || "UNKNOWN_ERROR"
                : transcriptionPath.slice(6);
            const friendlyMsg = errorCodeToMessage(errorCode);
            if (!cancelled) {
              setSttError({
                message: friendlyMsg,
                errorCode,
                retryable: isRetryable(errorCode),
              });
              setSttStatus("failed");
            }
            if (!cancelled) {
              setData((prev) =>
                prev
                  ? {
                      ...prev,
                      transcriptionfilepath: null,
                      transcription_source_type: null,
                      transcription_status: "FAILED",
                    }
                  : prev
              );
            }
            return;
          } else if (dbStatus === "COMPLETED" || transcriptionPath?.trim()) {
            if (!cancelled) setSttStatus("done");
          } else if (cfg.mode === "none") {
            if (!cancelled) setSttStatus("no_rule");
            transcriptionPath = null;
          } else if (cfg.mode === "import") {
            transcriptionPath = null;
          } else if (cfg.mode === "stt") {
            if (!cancelled) {
              setSttGenerating(true);
              setSttStatus("generating");
              setSttError(null);
            }

            interactionMetaRef.current = {
              iid,
              filePath,
              fileSourceType,
              platformId,
              appId,
              ani: normalized.ani || null,
              dnis: normalized.dnis || null,
              extension: normalized.extension || null,
              duration: normalized.duration || null,
              orgId: normalized.organizationId || null,
            };

            try {
              const genRes = await fetch("/api/transcription-generate", {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
                },
                body: JSON.stringify({
                  interactionId: iid,
                  filePath,
                  fileSourceType,
                  platformId,
                  appId,
                  ani: normalized.ani || null,
                  dnis: normalized.dnis || null,
                  extension: normalized.extension || null,
                  duration: normalized.duration || null,
                  orgId: normalized.organizationId || null,
                }),
              });

              const genData = await genRes.json().catch(() => ({}));

              if (genRes.ok) {
                transcriptionPath = genData.savedPath;
                transcriptionSourceType = fileSourceType;
                if (!cancelled) setSttStatus("done");
                if (
                  transcriptionPath &&
                  !transcriptionPath.startsWith("ERROR:") &&
                  transcriptionPath !== "PROCESSING"
                ) {
                  setStableTranscriptionPath(transcriptionPath);
                }
                fetch("/api/workFlow/getRuleStats", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
                  },
                }).catch(() => {});
              } else {
                const errCode = genData.errorCode || "UNKNOWN_ERROR";
                const errMsg = genData.message || errorCodeToMessage(errCode);
                if (!cancelled) {
                  setSttError({
                    message: errMsg,
                    errorCode: errCode,
                    retryable: genData.retryable ?? isRetryable(errCode),
                  });
                  setSttStatus("failed");
                }
                transcriptionPath = null;
              }
            } catch (genErr) {
              if (!cancelled) {
                setSttError({
                  message:
                    "Network error — could not reach transcription service. Check your connection.",
                  errorCode: "NETWORK_ERROR",
                  retryable: true,
                });
                setSttStatus("failed");
              }
              transcriptionPath = null;
            } finally {
              if (!cancelled) setSttGenerating(false);
            }
          }

          if (!cancelled) {
            setData((prev) =>
              prev
                ? {
                    ...prev,
                    transcriptionfilepath: transcriptionPath,
                    transcription_source_type: transcriptionSourceType,
                  }
                : prev
            );
            if (
              transcriptionPath &&
              !transcriptionPath.startsWith("ERROR:") &&
              transcriptionPath !== "PROCESSING"
            ) {
              setStableTranscriptionPath(transcriptionPath);
            }
          }
        } catch (cfgErr) {
          console.error("[transcription] config error:", cfgErr.message);
        }
      };

      loadAudio();
      loadTranscription();
    };

    run();
    return () => {
      cancelled = true;
      cancelledBox.current = true;
    };
  }, [id, normalizeInteraction]);

  const handleRetrieveCall = useCallback(async () => {
    const fileSourceType = data?.fileSourceType || data?.file_source_type;
    const iid = data?.id || id;
    if (!data?.fileLocation) return;

    try {
      setAudioFetching(true);
      setAudioError(null);
      const res = await fetch(
        `/api/audio?filePath=${encodeURIComponent(
          data.fileLocation
        )}&interactionId=${iid}&fileSourceType=${encodeURIComponent(
          fileSourceType ?? ""
        )}&actionType=retrieve&auth=${encodeURIComponent(
          process.env.NEXT_PUBLIC_API_TOKEN || ""
        )}`,
        {
          headers: {
            Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
          },
        }
      );
      if (res.ok) {
        const resData = await res.json();
        if (resData.status === "retrieving") {
          setArchiveStatus("retrieving");
          setAudioError("The call is retrieving...");
          setAudioUrl(null);
          setTimeout(() => {
            loadAudioRef.current?.(true);
          }, 15000);
        }
      } else {
        console.error("Retrieve request failed");
        setAudioError("Failed to initiate retrieval.");
      }
    } catch (err) {
      console.error("[retrieveCall] error:", err.message);
      setAudioError("Failed to initiate retrieval.");
    } finally {
      setAudioFetching(false);
    }
  }, [data, id]);

  const downloadAudio = async () => {
    const user = getSessionUser();
    const iid = data?.id || id;
    const cid = data?.callId || data?.call_id || iid;
    if (!data?.fileLocation) return;

    const tPath = stableTranscriptionPath || data?.transcriptionfilepath;
    const tSrcType =
      data?.transcription_source_type || data?.fileSourceType || "local";
    const hasTranscription = !!tPath?.trim();

    try {
      const res = await fetch("/api/interactions/download", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`,
          loggedInUserId: user?.userId,
          userName: user?.userFullName,
        },
        body: JSON.stringify({
          fileLocation: data.fileLocation,
          fileSourceType: data.fileSourceType,
          transcriptionPath: null, // Always download the raw media file directly (never a zip archive)
          transcriptionSourceType: null,
          callId: cid,
          fileExtension: fileExtension || "wav",
        }),
      });

      if (res.ok) {
        const blob = await res.blob();
        const downloadUrl = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = downloadUrl;
        a.download = `${cid}.${fileExtension || "wav"}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000);
      } else {
        console.error("Download failed.");
      }
    } catch (err) {
      console.error("Download failed.");
    }
  };

  useEffect(() => {
    return () => {
      if (audioBlobRef.current) URL.revokeObjectURL(audioBlobRef.current);
    };
  }, []);

  if (!id) return null;

  // Show unauthorized message only after privileges have resolved negatively
  if (privilegesLoaded && !hasPrivilege(PRIVILEGES.VIEW)) {
    return (
      <Dialog open={!!id} onOpenChange={(open) => !open && onClose()}>
        <DialogContent className="!max-w-[90vw] !w-[90vw] h-auto max-h-[85vh] p-6 bg-background border border-border shadow-2xl rounded-2xl flex items-center justify-center">
          <DialogTitle className="sr-only">Unauthorized Access</DialogTitle>
          <div className="text-xs text-muted-foreground text-center">
            You do not have permission to view this interaction.
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  const dialogWidthClass = "!max-w-[90vw] !w-[90vw]";

  const safeData = data || {
    id: id,
    callId: null,
    fileLocation: null,
    fileSourceType: null,
    transcriptionfilepath: null,
  };

  return (
    <Dialog open={!!id} onOpenChange={(open) => !open && onClose()}>
      <DialogContent hideCloseButton={true} className={`${dialogWidthClass} h-auto max-h-[85vh] p-6 bg-background border border-border shadow-2xl rounded-2xl flex flex-col overflow-visible`}>
        <DialogTitle className="sr-only">Playback Interaction</DialogTitle>
        <DialogDescription className="sr-only">
          Playback video/audio player and view details/transcription for the selected interaction.
        </DialogDescription>
        <div className="flex-1 min-h-0 overflow-visible pr-1">
          <InterationToolbar
            formData={safeData}
            Status={null}
            audioUrl={audioUrl}
            audioFetching={audioFetching}
            fileExtension={fileExtension}
            audioError={audioError}
            sttGenerating={sttGenerating}
            sttError={sttError}
            sttStatus={sttStatus}
            transcriptionMode={transcriptionMode}
            grantedPrivileges={grantedPrivileges}
            onRetryTranscription={handleRetryTranscription}
            stableTranscriptionPath={stableTranscriptionPath}
            archiveStatus={archiveStatus}
            onRetrieve={handleRetrieveCall}
            onBack={onClose}
            showTranscription={hasPrivilege(PRIVILEGES.TRANSCRIPTION)}
            downloadNode={
              <div className="flex items-center gap-2">
                <Button
                  onClick={downloadAudio}
                  disabled={!audioUrl || !!audioError || audioFetching}
                  className="text-xs px-3 gap-1.5 h-7 flex items-center shadow-md rounded-lg font-medium"
                >
                  <FaDownload className="h-3 w-3" /> Download Call
                </Button>
                <Button
                  variant="outline"
                  size="icon"
                  className="h-7 w-7 shadow-md rounded-lg flex items-center justify-center hover:bg-muted text-muted-foreground hover:text-foreground transition-colors"
                  onClick={onClose}
                  title="Close player"
                >
                  <X className="h-4 w-4" />
                </Button>
              </div>
            }
          />
        </div>
      </DialogContent>
    </Dialog>
  );
}
