"use client";
import jsPDF from "jspdf";
import "jspdf-autotable"; // ✅ This line registers autoTable to jsPDF
import * as XLSX from "xlsx";
const formatExportDateTime = (dateString) => {
  if (!dateString) return "-";
  const date = new Date(dateString);

  const options = {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  };

  return date.toLocaleString("en-GB", options);
};

const exportToExcelReport = (data, userName, fileName) => {
  try {
    const dateTime = new Date().toLocaleString();
    const headers = Object.keys(data[0]);

    // const worksheetData = [
    //   headers,
    //   ...data.map((row) => headers.map((header) => row[header] || "")),
    // ];
    const worksheetData = [
      headers,
      ...data.map((row) =>
        headers.map((header) => {
          if (header === "EvaluationDate") {
            return formatExportDateTime(row[header]);
          }
          return row[header] || "";
        })
      ),
    ];

    const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
    worksheet["!cols"] = headers.map(() => ({ wch: 25 }));

    const footerStartRow = worksheetData.length + 2;
    XLSX.utils.sheet_add_aoa(
      worksheet,
      [[], [], [`Generated by: ${userName}`], [`Generated on: ${dateTime}`]],
      { origin: `A${footerStartRow}` }
    );

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(
      workbook,
      worksheet,
      "Average_Evaluation_Report"
    );

    const excelBuffer = XLSX.write(workbook, {
      bookType: "xlsx",
      type: "array",
    });

    const blob = new Blob([excelBuffer], { type: "application/octet-stream" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.setAttribute("download", `${fileName}.xlsx`);
    link.click();
    URL.revokeObjectURL(link.href);
  } catch (error) {
    console.error("Excel export error:", error);
    alert("An error occurred while exporting the Excel file.");
  }
};

const exportToCSVReport = (data, userName, fileName) => {
  try {
    const dateTime = new Date().toLocaleString();
    const headers = Object.keys(data[0]);

    // const csvContent = [
    //   headers.join(","),
    //   ...data.map((row) =>
    //     headers
    //       .map((header) => {
    //         const value = row[header] != null ? row[header].toString() : "";
    //         return `"${value.replace(/"/g, '""')}"`;
    //       })
    //       .join(",")
    //   ),
    //   "",
    //   `"Generated by: ${userName}"`,
    //   `"Generated on: ${dateTime}"`,
    // ].join("\n");
    const csvContent = [
      headers.join(","),
      ...data.map((row) =>
        headers
          .map((header) => {
            let value = row[header] != null ? row[header].toString() : "";
            if (header === "EvaluationDate") {
              value = formatExportDateTime(row[header]);
            }
            return `"${value.replace(/"/g, '""')}"`;
          })
          .join(",")
      ),
      "",
      `"Generated by: ${userName}"`,
      `"Generated on: ${dateTime}"`,
    ].join("\n");

    const blob = new Blob(["\ufeff" + csvContent], {
      type: "text/csv;charset=utf-8;",
    });

    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.setAttribute("download", `${fileName}.csv`);
    link.click();
    URL.revokeObjectURL(link.href);
  } catch (error) {
    console.error("CSV export error:", error);
    alert("An error occurred while exporting the CSV file.");
  }
};

const exportToPDFReport = (data, userName, fileName) => {
  try {
    const dateTime = new Date().toLocaleString();
    const headers = Object.keys(data[0]);

    const formattedData = data.map((row) => {
      const wrappedRow = { ...row };
      ["Team/Organization Name"].forEach((field) => {
        if (row[field]) {
          const items = row[field].split(",");
          wrappedRow[field] = items
            .map(
              (item, index) =>
                `${item.trim()}${(index + 1) % 5 === 0 ? "\n" : ""}`
            )
            .join(", ");
        }
        if (row["EvaluationDate"]) {
          wrappedRow["EvaluationDate"] = formatExportDateTime(
            row["EvaluationDate"]
          );
        }
      });
      return wrappedRow;
    });

    const doc = new jsPDF({ orientation: "landscape", format: "a3" });
    const rows = formattedData.map((row) =>
      headers.map((header) => row[header] || "")
    );

    doc.autoTable({
      head: [headers],
      body: rows,
      startY: 20,
      styles: {
        fontSize: 8,
        overflow: "linebreak",
        cellWidth: "wrap",
      },
      theme: "grid",
      tableWidth: "auto",
      margin: { top: 20, bottom: 10, left: 10, right: 10 },
    });

    doc.setFontSize(10);
    doc.text(`Generated by: ${userName}`, 10, doc.lastAutoTable.finalY + 10);
    doc.text(`Generated on: ${dateTime}`, 10, doc.lastAutoTable.finalY + 20);

    doc.save(`${fileName}.pdf`);
  } catch (error) {
    console.error("PDF export error:", error);
    alert("An error occurred while exporting the PDF file.");
  }
};

const exportToPDFImageReport = (data, userName, fileName) => {
  const chartCanvas = document.querySelector("canvas");
  if (!chartCanvas) {
    alert("No chart available to export.");
    return;
  }

  const chartImage = chartCanvas.toDataURL("image/png", 1.0);
  const doc = new jsPDF("landscape", "pt", "a4");

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.addImage(chartImage, "PNG", 40, 40, pageWidth - 80, pageHeight - 160);
  doc.setFontSize(10);
  doc.text(`Generated By: ${userName || "Unknown"}`, 40, pageHeight - 60);
  doc.text(`Generated At: ${new Date().toLocaleString()}`, 40, pageHeight - 45);
  doc.save(`${fileName}.pdf`);
};

const exportToPNGReport = (data, userName, fileName) => {
  const chartCanvas = document.querySelector("canvas");
  if (!chartCanvas) {
    alert("No chart available to download.");
    return;
  }

  // Create a clone of the canvas to preserve original chart
  const exportCanvas = document.createElement("canvas");
  exportCanvas.width = chartCanvas.width;
  exportCanvas.height = chartCanvas.height;
  const ctx = exportCanvas.getContext("2d");

  // Draw the original chart image onto the new canvas
  ctx.drawImage(chartCanvas, 0, 0);

  // Add watermark: user name and timestamp
  ctx.font = "16px Arial";
  ctx.fillStyle = "rgba(0, 0, 0, 0.7)";
  ctx.fillText(
    `Generated By: ${userName || "Unknown"}`,
    20,
    exportCanvas.height - 40
  );
  ctx.fillText(
    `Generated At: ${new Date().toLocaleString()}`,
    20,
    exportCanvas.height - 20
  );

  // Export as PNG
  const imageData = exportCanvas.toDataURL("image/png", 1.0);
  const link = document.createElement("a");
  link.href = imageData;
  link.download = `${fileName}.png`;
  link.click();
};
export {
  exportToExcelReport,
  exportToCSVReport,
  exportToPDFReport,
  exportToPDFImageReport,
  exportToPNGReport,
};
